title: Auxiliatura Administracion de bases de datos II/2023
description: "Todo el contenido estara disponible por este medio"
author:
  name: "AdminBD"
  email: "churaalex57@gmail.com"
  url: "https:alexchura1.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "AdminBD"
year : "2023"
