title: Mi blog Personal
description: "Un pequeño espacio de aprendizaje"
author:
  name: "SrGalletito"
  email: "churaalex56@gmail.com"
  url: "https:srgalletitoo.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "SrGalletito"
year : "2023"
